Señas de nuestra empresa 
Nos dedicamos a los videojuegos y nos componemos de unos 50 empleados. 
Queremos buscar una nueva oficina sabiendo que:
-Contamos con 20 desarrolladores, 20 UX/UI y 10 ejecutivos.
Y queremos además:
    - Existan compañías de Software cerca.
    - Buen ratio entre grandes compañías y start-ups
    - Intentar que existan empresas que pueden ayudar a nuestros empleados(comercios, ¿Restaurantes?)
    - Intentar que no existan compañias con muchos años

Con este ejercicio se quiere verificar si simplemente con una aproximanción visual y representativa de los datos es suficiente o hace falta una mayor comprensión de los datos para poder encontrar el mejor punto

In [1]:
from pymongo import MongoClient
client = MongoClient()
db = client.companies
import pandas as pd
import re

In [2]:
bla = db.companies.find({ "$and": [ { "offices.latitude": {"$exists": True,"$ne":None} },{ "offices.longitude": {"$exists": True,"$ne":None} }, {"founded_year" : {"$gte": 2000} }, {'deadpooled_year': {"$eq":None}},{'number_of_employees':{'$ne':None}}]},{'name':1,'_id':0,'founded_year': 1, 'number_of_employees':1,'offices.latitude':1, 'offices.longitude':1,'category_code':1,'total_money_raised':1})  
df = pd.DataFrame(bla)

In [3]:
df.info()

#for a in df["offices"]:
    #print(a[0]["latitude"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3970 entries, 0 to 3969
Data columns (total 6 columns):
category_code          3957 non-null object
founded_year           3970 non-null int64
name                   3970 non-null object
number_of_employees    3970 non-null int64
offices                3970 non-null object
total_money_raised     3970 non-null object
dtypes: int64(2), object(4)
memory usage: 186.2+ KB

In [4]:
#crear columna latitud
def latitud(coord): 
    return coord[0]['latitude']

#crear columna longitud   
def longitud(coord): 
    return coord[0]['longitude']

# crear nuevas columnas en el DataFrame 
def insert_latlong(df):   
    df['latitude'] = df['offices'].apply(latitud)
    df['longitude'] = df['offices'].apply(longitud)
    return df

In [6]:
df= insert_latlong(df)
df = df.drop(['offices'], axis=1)
df

,category_code,founded_year,name,number_of_employees,total_money_raised,latitude,longitude
0,web,2001,TechnologyGuide,10,$0,39.066850,-84.351532
1,news,2004,Digg,60,$45M,37.764726,-122.394523
2,social,2004,Facebook,5299,$2.43B,37.416050,-122.151801
3,web,2006,Geni,18,$16.5M,34.090368,-118.393064
4,social,2006,Twitter,1300,$1.16B,37.776805,-122.416924
5,news,2007,Scribd,50,$25.8M,37.789634,-122.404052
6,social,2007,MeetMoi,15,$5.58M,40.757929,-73.985506
7,games_video,2006,Joost,0,$45M,40.746497,-74.009447
8,web,2002,Plaxo,50,$28.3M,37.387845,-122.055197
9,search,2006,Powerset,60,$22.5M,37.778613,-122.395289
10,advertising,2002,Technorati,35,$32.1M,37.779558,-122.393041
11,web,2007,Mahalo,40,$21M,34.017606,-118.487267
12,games_video,2006,Kyte,40,$23.4M,37.788482,-122.409173
13,web,2007,CriticalMetrics,4,$100k,37.269175,-119.306607
14,mobile,2005,Jingle Networks,35,$88.7M,37.480999,-122.173887
15,web,2002,Meetup,75,$18.3M,40.726040,-73.995722
16,security,2005,LifeLock,644,$178M,33.429859,-111.938739
17,photo_video,2002,SmugMug,62,$0,37.390056,-122.067692
18,mobile,2005,Jajah,110,$33M,37.423390,-122.089951
19,games_video,2005,YouTube,0,$11.5M,37.627971,-122.426804
20,games_video,2007,Livestream,120,$14.7M,40.726155,-73.995625
21,games_video,2007,AdaptiveBlue,15,$24M,40.801358,-74.337200
22,games_video,2004,Pando Networks,23,$11M,40.722655,-73.998730
23,mobile,2006,GrandCentral,3,$4M,37.465645,-121.932202
24,web,2003,Ikan,5,$0,41.049051,-73.563878
25,web,2007,Pownce,6,$0,37.762541,-122.397224
26,search,2006,Spock,30,$7M,37.488336,-122.217964
27,web,2007,SodaHead,25,$12.7M,37.269175,-119.306607
28,games_video,2006,CastTV,0,$3.1M,37.780716,-122.393913
29,web,2005,ClipBlast!,15,$0,34.155211,-118.756618
...,...,...,...,...,...,...,...
3940,network_hosting,2000,Sanera,89,$0,37.395470,-122.027190
3941,software,2008,Continuity Engine,11,$7.84M,41.327918,-73.243552
3942,social,2008,FundRazr,6,C$325k,49.284394,-123.109262
3943,ecommerce,2008,Pipit Interactive,10,$900k,34.045499,-118.470360
3944,ecommerce,2009,Bookwhen,2,$0,51.771426,-1.258105
3945,mobile,2009,pTracker,2,$0,30.268735,-97.745209
3946,games_video,2007,DJ Nitrogen,8,$0,37.784174,-122.449408
3947,enterprise,2001,InfoLogix,206,$3M,40.192329,-75.106923
3948,search,2008,Superkix,5,$0,25.960908,-80.127765
3949,search,2007,Semanti,7,$0,53.483151,-113.478872
3950,software,2000,optionsXpress,305,$0,41.880626,-87.635607
3951,software,2007,Meeho!,5,$0,55.752525,12.393304
3952,software,2007,ALOT,50,$0,40.726160,-74.006023
3953,consulting,2007,Business and Technology Strategies,5,$0,28.792491,-81.383874
3954,games_video,2008,Fictionaut,2,$0,40.759795,-73.916127
3955,security,2006,Track and Locate,10,$0,-33.815217,151.002324
3956,web,2008,Conversition,10,$0,40.756054,-73.986951
3957,enterprise,2008,Jelli,12,$16.6M,37.559090,-122.321836
3958,software,2006,PubliAtis,10,€1M,48.869995,2.340695
3959,games_video,2009,Tiny Speck,45,$17.2M,49.282455,-123.109217
3960,games_video,2007,My TV Shows,2,$0,38.752367,-9.146221
3961,other,2008,Hellocoton,4,$0,48.831850,2.338986
3962,network_hosting,2004,AwardSpace,35,$0,54.323738,10.166515
3963,search,2008,Buddhacom,8,$0,43.676252,-79.400859
3964,public_relations,2009,SEO Sumo,5,$0,25.723408,-80.306331
3965,advertising,2009,InstantQ,3,$0,37.369195,-122.036849
3966,enterprise,2004,NextLabs,100,$0,37.553121,-122.301534
3967,mobile,2009,acrossair,6,$0,51.517742,-0.116537
3968,consulting,2009,MyChances,2,$0,39.394564,-119.812079
3969,mobile,2009,Getyoo,10,€1.13M,50.839970,4.346472

In [7]:
def geoj(a,b):
    return {'type':'Point', 'coordinates':[a,b]}

df['geojson'] = df.apply(lambda x: geoj(x['longitude'], x['latitude']),axis=1)
df

,category_code,founded_year,name,number_of_employees,total_money_raised,latitude,longitude,geojson
0,web,2001,TechnologyGuide,10,$0,39.066850,-84.351532,"{'type': 'Point', 'coordinates': [-84.351532, ..."
1,news,2004,Digg,60,$45M,37.764726,-122.394523,"{'type': 'Point', 'coordinates': [-122.394523,..."
2,social,2004,Facebook,5299,$2.43B,37.416050,-122.151801,"{'type': 'Point', 'coordinates': [-122.151801,..."
3,web,2006,Geni,18,$16.5M,34.090368,-118.393064,"{'type': 'Point', 'coordinates': [-118.393064,..."
4,social,2006,Twitter,1300,$1.16B,37.776805,-122.416924,"{'type': 'Point', 'coordinates': [-122.4169244..."
5,news,2007,Scribd,50,$25.8M,37.789634,-122.404052,"{'type': 'Point', 'coordinates': [-122.404052,..."
6,social,2007,MeetMoi,15,$5.58M,40.757929,-73.985506,"{'type': 'Point', 'coordinates': [-73.985506, ..."
7,games_video,2006,Joost,0,$45M,40.746497,-74.009447,"{'type': 'Point', 'coordinates': [-74.0094471,..."
8,web,2002,Plaxo,50,$28.3M,37.387845,-122.055197,"{'type': 'Point', 'coordinates': [-122.055197,..."
9,search,2006,Powerset,60,$22.5M,37.778613,-122.395289,"{'type': 'Point', 'coordinates': [-122.395289,..."
10,advertising,2002,Technorati,35,$32.1M,37.779558,-122.393041,"{'type': 'Point', 'coordinates': [-122.393041,..."
11,web,2007,Mahalo,40,$21M,34.017606,-118.487267,"{'type': 'Point', 'coordinates': [-118.487267,..."
12,games_video,2006,Kyte,40,$23.4M,37.788482,-122.409173,"{'type': 'Point', 'coordinates': [-122.409173,..."
13,web,2007,CriticalMetrics,4,$100k,37.269175,-119.306607,"{'type': 'Point', 'coordinates': [-119.306607,..."
14,mobile,2005,Jingle Networks,35,$88.7M,37.480999,-122.173887,"{'type': 'Point', 'coordinates': [-122.173887,..."
15,web,2002,Meetup,75,$18.3M,40.726040,-73.995722,"{'type': 'Point', 'coordinates': [-73.995722, ..."
16,security,2005,LifeLock,644,$178M,33.429859,-111.938739,"{'type': 'Point', 'coordinates': [-111.938739,..."
17,photo_video,2002,SmugMug,62,$0,37.390056,-122.067692,"{'type': 'Point', 'coordinates': [-122.067692,..."
18,mobile,2005,Jajah,110,$33M,37.423390,-122.089951,"{'type': 'Point', 'coordinates': [-122.0899512..."
19,games_video,2005,YouTube,0,$11.5M,37.627971,-122.426804,"{'type': 'Point', 'coordinates': [-122.426804,..."
20,games_video,2007,Livestream,120,$14.7M,40.726155,-73.995625,"{'type': 'Point', 'coordinates': [-73.995625, ..."
21,games_video,2007,AdaptiveBlue,15,$24M,40.801358,-74.337200,"{'type': 'Point', 'coordinates': [-74.3372, 40..."
22,games_video,2004,Pando Networks,23,$11M,40.722655,-73.998730,"{'type': 'Point', 'coordinates': [-73.99873, 4..."
23,mobile,2006,GrandCentral,3,$4M,37.465645,-121.932202,"{'type': 'Point', 'coordinates': [-121.932202,..."
24,web,2003,Ikan,5,$0,41.049051,-73.563878,"{'type': 'Point', 'coordinates': [-73.563878, ..."
25,web,2007,Pownce,6,$0,37.762541,-122.397224,"{'type': 'Point', 'coordinates': [-122.397224,..."
26,search,2006,Spock,30,$7M,37.488336,-122.217964,"{'type': 'Point', 'coordinates': [-122.217964,..."
27,web,2007,SodaHead,25,$12.7M,37.269175,-119.306607,"{'type': 'Point', 'coordinates': [-119.306607,..."
28,games_video,2006,CastTV,0,$3.1M,37.780716,-122.393913,"{'type': 'Point', 'coordinates': [-122.393913,..."
29,web,2005,ClipBlast!,15,$0,34.155211,-118.756618,"{'type': 'Point', 'coordinates': [-118.756618,..."
...,...,...,...,...,...,...,...,...
3940,network_hosting,2000,Sanera,89,$0,37.395470,-122.027190,"{'type': 'Point', 'coordinates': [-122.02719, ..."
3941,software,2008,Continuity Engine,11,$7.84M,41.327918,-73.243552,"{'type': 'Point', 'coordinates': [-73.2435522,..."
3942,social,2008,FundRazr,6,C$325k,49.284394,-123.109262,"{'type': 'Point', 'coordinates': [-123.1092622..."
3943,ecommerce,2008,Pipit Interactive,10,$900k,34.045499,-118.470360,"{'type': 'Point', 'coordinates': [-118.47036, ..."
3944,ecommerce,2009,Bookwhen,2,$0,51.771426,-1.258105,"{'type': 'Point', 'coordinates': [-1.2581049, ..."
3945,mobile,2009,pTracker,2,$0,30.268735,-97.745209,"{'type': 'Point', 'coordinates': [-97.745209, ..."
3946,games_video,2007,DJ Nitrogen,8,$0,37.784174,-122.449408,"{'type': 'Point', 'coordinates': [-122.4494082..."
3947,enterprise,2001,InfoLogix,206,$3M,40.192329,-75.106923,"{'type': 'Point', 'coordinates': [-75.1069232,..."
3948,search,2008,Superkix,5,$0,25.960908,-80.127765,"{'type': 'Point', 'coordinates': [-80.1277653,..."
3949,search,2007,Semanti,7,$0,53.483151,-113.478872,"{'type': 'Point', 'coordinates': [-113.478872,..."
3950,software,2000,optionsXpress,305,$0,41.880626,-87.635607,"{'type': 'Point', 'coordinates': [-87.6356066,..."
3951,software,2007,Meeho!,5,$0,55.752525,12.393304,"{'type': 'Point', 'coordinates': [12.3933043, ..."
3952,software,2007,ALOT,50,$0,40.726160,-74.006023,"{'type': 'Point', 'coordinates': [-74.006023, ..."
3953,consulting,2007,Business and Technology Strategies,5,$0,28.792491,-81.383874,"{'type': 'Point', 'coordinates': [-81.383874, ..."
3954,games_video,2008,Fictionaut,2,$0,40.759795,-73.916127,"{'type': 'Point', 'coordinates': [-73.9161267,..."
3955,security,2006,Track and Locate,10,$0,-33.815217,151.002324,"{'type': 'Point', 'coordinates': [151.002324, ..."
3956,web,2008,Conversition,10,$0,40.756054,-73.986951,"{'type': 'Point', 'coordinates': [-73.986951, ..."
3957,enterprise,2008,Jelli,12,$16.6M,37.559090,-122.321836,"{'type': 'Point', 'coordinates': [-122.321836,..."
3958,software,2006,PubliAtis,10,€1M,48.869995,2.340695,"{'type': 'Point', 'coordinates': [2.3406954, 4..."
3959,games_video,2009,Tiny Speck,45,$17.2M,49.282455,-123.109217,"{'type': 'Point', 'coordinates': [-123.109217,..."
3960,games_video,2007,My TV Shows,2,$0,38.752367,-9.146221,"{'type': 'Point', 'coordinates': [-9.1462209, ..."
3961,other,2008,Hellocoton,4,$0,48.831850,2.338986,"{'type': 'Point', 'coordinates': [2.3389864, 4..."
3962,network_hosting,2004,AwardSpace,35,$0,54.323738,10.166515,"{'type': 'Point', 'coordinates': [10.1665152, ..."
3963,search,2008,Buddhacom,8,$0,43.676252,-79.400859,"{'type': 'Point', 'coordinates': [-79.4008589,..."
3964,public_relations,2009,SEO Sumo,5,$0,25.723408,-80.306331,"{'type': 'Point', 'coordinates': [-80.306331, ..."
3965,advertising,2009,InstantQ,3,$0,37.369195,-122.036849,"{'type': 'Point', 'coordinates': [-122.036849,..."
3966,enterprise,2004,NextLabs,100,$0,37.553121,-122.301534,"{'type': 'Point', 'coordinates': [-122.301534,..."
3967,mobile,2009,acrossair,6,$0,51.517742,-0.116537,"{'type': 'Point', 'coordinates': [-0.1165365, ..."
3968,consulting,2009,MyChances,2,$0,39.394564,-119.812079,"{'type': 'Point', 'coordinates': [-119.8120795..."
3969,mobile,2009,Getyoo,10,€1.13M,50.839970,4.346472,"{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [7]:
df.to_json("dflimpia.json",orient="records",lines=True)