In [5]:
import pandas as pd
data = pd.read_csv('./vehicles/vehicles_messy.csv')
display(data.columns)
print(data.shape)
data.head()

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb'],
      dtype='object')

(37843, 83)

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [10]:
null_cols = data.isnull().sum()
display(null_cols[null_cols > 0])
null_cols[null_cols > 0].index

cylinders       123
displ           120
drive          1189
eng_dscr      15403
trany            11
guzzler       35562
trans_dscr    22796
tCharger      32657
sCharger      37177
atvType       34771
fuelType2     36435
rangeA        36440
evMotor       37281
mfrCode       30818
c240Dscr      37806
c240bDscr     37807
startStop     31705
dtype: int64

Index(['cylinders', 'displ', 'drive', 'eng_dscr', 'trany', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'c240bDscr', 'startStop'],
      dtype='object')

In [11]:
drop_cols = list(null_cols[null_cols > 10000].index)
print(drop_cols)
data = data.drop(drop_cols, axis=1)

['eng_dscr', 'guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'c240bDscr', 'startStop']

In [14]:
null_displ = data[(data['displ'].isnull()==True)]
null_displ = null_displ[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]
null_displ

,year,make,model,trany,drive,fuelType,cylinders,displ
7138,2000,Nissan,Altra EV,NaN,NaN,Electricity,NaN,NaN
7139,2000,Toyota,RAV4 EV,NaN,2-Wheel Drive,Electricity,NaN,NaN
8143,2001,Toyota,RAV4 EV,NaN,2-Wheel Drive,Electricity,NaN,NaN
8144,2001,Ford,Th!nk,NaN,NaN,Electricity,NaN,NaN
8146,2001,Ford,Explorer USPS Electric,NaN,2-Wheel Drive,Electricity,NaN,NaN
8147,2001,Nissan,Hyper-Mini,NaN,NaN,Electricity,NaN,NaN
9212,2002,Toyota,RAV4 EV,NaN,2-Wheel Drive,Electricity,NaN,NaN
9213,2002,Ford,Explorer USPS Electric,NaN,2-Wheel Drive,Electricity,NaN,NaN
10329,2003,Toyota,RAV4 EV,NaN,2-Wheel Drive,Electricity,NaN,NaN
21413,1985,Subaru,RX Turbo,Manual 5-spd,4-Wheel Drive,Regular,NaN,NaN
21414,1985,Subaru,RX Turbo,Manual 5-spd,4-Wheel Drive,Regular,NaN,NaN
23026,2001,Ford,Ranger Pickup 2WD,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23027,2000,Ford,Ranger Pickup 2WD,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23028,2000,Ford,Ranger Pickup 2WD,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23029,1999,GMC,EV1,Automatic (A1),NaN,Electricity,NaN,NaN
23030,1999,GMC,EV1,Automatic (A1),NaN,Electricity,NaN,NaN
23032,1999,Honda,EV Plus,Automatic (A1),NaN,Electricity,NaN,NaN
23033,1999,Ford,Ranger Pickup 2WD,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23034,1999,Ford,Ranger Pickup 2WD,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23035,1999,Dodge,Caravan/Grand Caravan 2WD,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23036,1999,Plymouth,Voyager/Grand Voyager 2WD,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
23037,1998,Honda,EV Plus,Automatic (A1),NaN,Electricity,NaN,NaN
23038,1998,Chevrolet,S10 Electric,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23039,1998,Chevrolet,S10 Electric,Automatic (A1),2-Wheel Drive,Electricity,NaN,NaN
23040,2008,MINI,MiniE,Automatic (A1),NaN,Electricity,NaN,NaN
23041,2011,Nissan,Leaf,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
23137,2011,smart,fortwo electric drive cabriolet,Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
23138,2011,smart,fortwo electric drive coupe,Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
23807,2012,Mitsubishi,i-MiEV,Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
24051,2012,Azure Dynamics,Transit Connect Electric Van,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
...,...,...,...,...,...,...,...,...
29654,2016,Tesla,Model X AWD - P90D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
29671,2016,Chevrolet,Spark EV,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
29672,2016,Mercedes-Benz,B250e,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
29750,2016,Nissan,Leaf (24 kW-hr battery pack),Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
29751,2016,Nissan,Leaf (30 kW-hr battery pack),Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
29849,2016,Fiat,500e,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
29915,2016,BMW,i3 BEV,Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
29933,2016,Tesla,Model S (70 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
29934,2016,Tesla,Model S (85 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
29935,2016,Tesla,Model S (90 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
29936,2015,Tesla,Model S (90 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
29938,2016,Tesla,Model S AWD - 70D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
29939,2016,Tesla,Model S AWD - 85D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
29941,2016,Tesla,Model S AWD - 90D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
29942,2016,Tesla,Model S AWD - P85D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
29943,2016,Tesla,Model S AWD - P90D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
29999,2017,Mitsubishi,i-MiEV,Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
30141,2016,Tesla,Model S (75 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
30142,2016,Tesla,Model S AWD - 75D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
30143,2016,Tesla,Model X AWD - 75D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
30557,2017,Fiat,500e,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
30561,2016,BYD,e6,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
30784,2017,BMW,I3 BEV (60 Amp-hour battery),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
30785,2017,BMW,I3 BEV (94 Amp-hour battery),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
30786,2017,Mercedes-Benz,B250e,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
30969,2017,Kia,Soul Electric,Automatic (A1),Front-Wheel Drive,Electricity,NaN,NaN
30972,2016,Tesla,Model S (60 kW-hr battery pack),Automatic (A1),Rear-Wheel Drive,Electricity,NaN,NaN
30973,2016,Tesla,Model S AWD - 60D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
30974,2016,Tesla,Model S AWD - P100D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN
30975,2016,Tesla,Model X AWD - 60D,Automatic (A1),All-Wheel Drive,Electricity,NaN,NaN

In [15]:
data[['displ', 'cylinders']] = data[['displ', 'cylinders']].fillna(0)

In [20]:
test = data[(data['cylinders']==0) & (data['displ']!=0)]
test[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]

,year,make,model,trany,drive,fuelType,cylinders,displ
21506,1986,Mazda,RX-7,Manual 5-spd,Rear-Wheel Drive,Regular,0.0,1.3

In [29]:
test = data[(data['cylinders'] == 0) & (data['displ'] !=0 )]
test[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]

,year,make,model,trany,drive,fuelType,cylinders,displ
21506,1986,Mazda,RX-7,Manual 5-spd,Rear-Wheel Drive,Regular,0.0,1.3

In [30]:
data.loc[(data['cylinders']==0) & (data['displ']!=0), 'cylinders'] = 4

In [35]:
import numpy as np
low_variance = []

for col in data._get_numeric_data():
    minimum = min(data[col])
    ninety_perc = np.percentile(data[col], 90)
    if ninety_perc == minimum:
        low_variance.append(col)

print(low_variance)

['barrelsA08', 'charge120', 'charge240', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2A', 'co2TailpipeAGpm', 'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'fuelCostA08', 'ghgScoreA', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE', 'highwayUF', 'phevBlended', 'range', 'rangeCity', 'rangeCityA', 'rangeHwy', 'rangeHwyA', 'UCityA', 'UHighwayA', 'charge240b', 'phevCity', 'phevHwy', 'phevComb']

In [36]:
data = data.drop(low_variance, axis=1)

In [41]:
data.describe()
stats = data.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

,count,mean,std,min,25%,50%,75%,max,IQR
barrels08,37843.0,17.532506,4.575950,0.06,14.33087,17.347895,20.600625,47.087143,6.269755
city08,37843.0,17.941389,6.660360,6.00,15.00000,17.000000,20.000000,138.000000,5.000000
city08U,37843.0,4.042737,9.645820,0.00,0.00000,0.000000,0.000000,138.304000,0.000000
co2,37843.0,61.503713,153.387715,-1.00,-1.00000,-1.000000,-1.000000,847.000000,0.000000
co2TailpipeGpm,37843.0,473.179736,122.188847,0.00,388.00000,467.736842,555.437500,1269.571429,167.437500
comb08,37843.0,20.195809,6.623444,7.00,17.00000,19.000000,23.000000,124.000000,6.000000
comb08U,37843.0,4.549751,10.389994,0.00,0.00000,0.000000,0.000000,124.360100,0.000000
cylinders,37843.0,5.719446,1.778959,0.00,4.00000,6.000000,6.000000,16.000000,2.000000
displ,37843.0,3.307658,1.371982,0.00,2.20000,3.000000,4.300000,8.400000,2.100000
engId,37843.0,8860.308961,17829.683477,0.00,0.00000,211.000000,4505.000000,69102.000000,4505.000000
feScore,37843.0,-0.035145,2.379584,-1.00,-1.00000,-1.000000,-1.000000,10.000000,0.000000
fuelCost08,37843.0,1882.060090,510.280408,550.00,1500.00000,1850.000000,2200.000000,5800.000000,700.000000
ghgScore,37843.0,-0.037206,2.374338,-1.00,-1.00000,-1.000000,-1.000000,10.000000,0.000000
highway08,37843.0,24.104881,6.963192,9.00,20.00000,24.000000,27.000000,111.000000,7.000000
highway08U,37843.0,5.438467,11.936327,0.00,0.00000,0.000000,0.000000,111.370000,0.000000
hlv,37843.0,2.026214,5.947989,0.00,0.00000,0.000000,0.000000,49.000000,0.000000
hpv,37843.0,10.424332,28.148770,0.00,0.00000,0.000000,0.000000,195.000000,0.000000
id,37843.0,19019.286235,11034.784855,1.00,9461.50000,18923.000000,28570.500000,38173.000000,19109.000000
lv2,37843.0,1.849219,4.429983,0.00,0.00000,0.000000,0.000000,41.000000,0.000000
lv4,37843.0,6.165658,9.743297,0.00,0.00000,0.000000,13.000000,55.000000,13.000000
pv2,37843.0,13.696113,31.269930,0.00,0.00000,0.000000,0.000000,194.000000,0.000000
pv4,37843.0,33.769125,45.914462,0.00,0.00000,0.000000,91.000000,192.000000,91.000000
UCity,37843.0,22.587229,9.350163,0.00,18.00000,21.000000,25.139300,197.577100,7.139300
UHighway,37843.0,33.619221,10.048326,0.00,27.10000,33.000000,38.109600,159.100000,11.009600
year,37843.0,2000.064398,10.390588,1984.00,1990.00000,2001.000000,2009.000000,2017.000000,19.000000
youSaveSpend,37843.0,-2658.999022,2553.098329,-22250.00,-4250.00000,-2500.000000,-750.000000,4000.000000,3500.000000

In [42]:
outliers = pd.DataFrame(columns=data.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data[(data[col] < lower) | 
                   (data[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)

/usr/local/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [46]:
outliers["Outlier"].value_counts()

highway08U        7299
comb08U           7299
city08U           7299
engId             6677
lv2               6250
pv2               6239
co2               5854
ghgScore          5815
feScore           5815
hlv               4615
hpv               4614
city08            1470
UCity             1440
lv4               1357
highway08          996
comb08             969
UHighway           893
cylinders          852
co2TailpipeGpm     830
youSaveSpend       604
fuelCost08         604
barrels08          432
displ               43
Name: Outlier, dtype: int64

In [50]:
print(len(set(data['trany'])))
data['trany'] = data['trany'].str.replace('-', '')
print(len(set(data['trany'])))

46
46

In [51]:
data['trany'] = data['trany'].str.replace('Automatic', 'Auto')
data['trany'] = data['trany'].str.replace('Auto\(', 'Auto ')
data['trany'] = data['trany'].str.replace('Manual\(', 'Manual ')
data['trany'] = data['trany'].str.replace('\(', '')
data['trany'] = data['trany'].str.replace('\)', '')
print(set(data['trany']))

{nan, 'Manual 5spd', 'Auto AMS9', 'Auto 7spd', 'Auto 6spd', 'Auto S8', 'Manual 7spd', 'Auto 3spd', 'Manual 3spd', 'Auto 5spd', 'Manual 4spd', 'Auto 8spd', 'Auto AM7', 'Auto 4spd', 'Auto AVS7', 'Auto AMS7', 'Auto AMS6', 'Manual M7', 'Auto S4', 'Auto 9spd', 'Manual 5 spd', 'Auto L3', 'Auto variable gear ratios', 'Manual 4spd Doubled', 'Auto AM6', 'Auto AM5', 'Auto A6', 'Auto S6', 'Auto A1', 'Auto AMS8', 'Auto S5', 'Auto L4', 'Manual 6spd', 'Auto AVS8', 'Auto AV', 'Auto AM8', 'Auto S9', 'Auto S7', 'Auto AVS6'}

In [52]:
print(len(set(data['trany'])))

39

In [53]:
before = len(data)
data = data.drop_duplicates()
after = len(data)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  0

In [54]:
select_columns = ['make', 'model', 'year', 'displ', 'cylinders', 
                  'trany', 'drive', 'VClass','fuelType','barrels08', 
                  'city08', 'highway08', 'comb08', 'co2TailpipeGpm', 'fuelCost08']

data = data[select_columns].drop_duplicates()
after = len(data)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  885

In [55]:
data.head()

,make,model,year,displ,cylinders,trany,drive,VClass,fuelType,barrels08,city08,highway08,comb08,co2TailpipeGpm,fuelCost08
0,Alfa Romeo,Spider Veloce 2000,1985,2.0,4.0,Manual 5spd,Rear-Wheel Drive,Two Seaters,Regular,15.695714,19,25,21,423.190476,1600
1,Ferrari,Testarossa,1985,4.9,12.0,Manual 5spd,Rear-Wheel Drive,Two Seaters,Regular,29.964545,9,14,11,807.909091,3050
2,Dodge,Charger,1985,2.2,4.0,Manual 5spd,Front-Wheel Drive,Subcompact Cars,Regular,12.207778,23,33,27,329.148148,1250
3,Dodge,B150/B250 Wagon 2WD,1985,5.2,8.0,Auto 3spd,Rear-Wheel Drive,Vans,Regular,29.964545,10,12,11,807.909091,3050
4,Subaru,Legacy AWD Turbo,1993,2.2,4.0,Manual 5spd,4-Wheel or All-Wheel Drive,Compact Cars,Premium,17.347895,17,23,19,467.736842,2150