# Shark KO

### Hipotesis
### How likely is it that a shark attack is lethal, and at which season are more often.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
unclean_data=pd.read_csv('GSAF5.csv', encoding = 'ISO-8859-1')# Had to add encoding because of an error of UnicodeDecodeError.
unclean_data.head() # Display first 5 rows of original data frame

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [3]:
unclean_data.columns # Verifying that all my columns are correctly written

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [4]:
null_cols = unclean_data.isnull().sum() 
null_cols[null_cols > 0]
print(null_cols)# Checking how many columns are null

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [5]:
unclean_data.isnull().sum().sum() # Adding total numbers of null

23109

In [6]:
drop_cols = list(null_cols[null_cols > 1000].index)
data = unclean_data.drop(drop_cols, axis=1)
data = data.drop(['Case Number.1','Case Number.2','original order','href formula','pdf','Investigator or Source','href','Case Number','Location','Name'], axis=1)
data.head()

,Date,Year,Type,Country,Area,Activity,Sex,Injury,Fatal (Y/N)
0,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Minor injury to thigh,N
1,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to hands,N
2,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to lower leg,N
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Surfing,M,Struck by fin on chest & leg,N
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Surfing,M,No injury: Knocked off board by shark,N

In [7]:
data = data.rename(columns={'Fatal (Y/N)':'Fatal'})
display(data)

,Date,Year,Type,Country,Area,Activity,Sex,Injury,Fatal
0,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Minor injury to thigh,N
1,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to hands,N
2,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to lower leg,N
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Surfing,M,Struck by fin on chest & leg,N
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Surfing,M,No injury: Knocked off board by shark,N
5,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Fishing,NaN,Shark rammed boat. No injury to occupant,N
6,11-Sep-16,2016,Unprovoked,USA,Florida,Wading,M,Minor injury to arm,N
7,07-Sep-16,2016,Unprovoked,USA,Hawaii,Swimming,F,Severe lacerations to shoulder & forearm,N
8,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Kite surfing,M,FATAL,Y
9,05-Sep-16,2016,Unprovoked,USA,South Carolina,Boogie boarding,F,Lacerations & punctures to lower right leg,N
10,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Surfing,M,"No inury, board broken in half by shark",N
11,04-Sep-16,2016,Unprovoked,USA,Florida,Body boarding,M,Foot bitten,N
12,01-Sep-16,2016,Unprovoked,USA,California,Spearfishing,M,Two toes broken & lacerated,N
13,29-Aug-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to right foot,N
14,29-Aug-16,2016,Unprovoked,USA,Florida,Surfing,M,Minor injury to ankle,N
15,27-Aug-16,2016,Unprovoked,REUNION,NaN,Surfing,M,"Right arm severed, ankle severely bitten",N
16,25-Aug-16,2016,Unprovoked,USA,Florida,Wading,M,Minor injury to ankle,N
17,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Snorkeling,M,Lacerations to left leg,N
18,06-Aug-16,2016,Unprovoked,USA,Hawaii,SUP Foil boarding,M,"No inury, shark & board collided",N
19,04-Aug-16,2016,Unprovoked,USA,Florida,Surfing,M,Big toe bitten,N
20,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Swimming,M,Lacerations to right hand,N
21,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,Swimming,M,Lacerations to leg,N
22,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Kayaking,M,"No injury, shark nudged kayak repeatedly",N
23,27-Jul-16,2016,Provoked,USA,Florida,Lobstering,M,Laceration to left forearm PROVOKED INCIDENT,N
24,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,Surfing,M,"No injury. Leg rope severed, knocked off board...",N
25,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Surfing,M,Lacerations to left leg,N
26,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Surfing,M,Calf bumped but no injury,N
27,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Spearfishing,M,Lacerations to face and right leg,N
28,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,Fishing,M,Laceration to left calf from hooked shark PROV...,N
29,17-Jul-16,2016,Boat,USA,Alabama,Fishing in Alabama Deep Fishing Rodeo,NaN,"No injury, shark bit trolling motor",N
...,...,...,...,...,...,...,...,...,...
5962,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,"Aircraft ditched in the sea, swimming ashore",M,Shark bumped him,N
5963,Before 1905,0,Unprovoked,BURMA,NaN,Bathing,M,Fatal x 2,Y
5964,A few years before 1938,0,Boat,ITALY,Adriatic Sea,Wooden fishing boat,M,No injury to occupant; shark capsized boat,N
5965,No date,0,Unprovoked,GREECE,Dodecanese Islands,Sponge diving,M,Head bitten,N
5966,Early 1930s,0,Unprovoked,BELIZE,NaN,Standing,M,FATAL,Y
5967,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,NaN,M,NaN,UNKNOWN
5968,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Swimming,NaN,FATAL,Y
5969,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Wading,F,Ankle bitten,N
5970,No date,0,Unprovoked,AUSTRALIA,NaN,Pearl diving,M,Lacerations to thigh,N
5971,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Swimming in pool formed by construction of a w...,M,"FATAL, leg severed",Y
5972,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,NaN,M,FATAL,Y
5973,Before 1921,0,Unprovoked,USA,Florida,Fishing,M,2-inch lacerations,N
5974,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,Swimming around anchored ship,M,Foot bitten,N
5975,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Crew swimming alongside their anchored ship,M,FATAL,Y
5976,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,4 men were bathing,M,FATAL,Y
5977,Before 1917,0,Unprovoked,FIJI,Moala Island,Wreck of large double sailing canoe,NaN,"FATAL, 18 people were killed by sharks, 2 sur...",Y
5978,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Swimming,M,"""Lost leg""",N
5979,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Fishing,M,"FATAL, body not recovered but shark was caught...",Y
5980,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Wading,M,"FATAL, leg stripped of flesh",Y
5981,Before 1911,0,Unprovoked,ASIA?,NaN,Swimming,M,Foot severed,N
5982,Circa 1862,0,Unprovoked,USA,Hawaii,NaN,F,Ankle bitten,N
5983,Before 1906,0,Unprovoked,AUSTRALIA,NaN,Fishing,M,"FATAL, knocked overboard by tail of shark & ca...",Y
5984,Before 1906,0,Unprovoked,AUSTRALIA,NaN,Fishing,M,FATAL,Y
5985,Before 1906,0,Unprovoked,AUSTRALIA,NaN,Fishing,M,FATAL,Y
5986,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,Swimming,M,FATAL,Y
5987,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Diving,M,FATAL,Y
5988,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Pearl diving,M,FATAL,Y
5989,1900-1905,0,Unprovoked,USA,North Carolina,Swimming,M,FATAL,Y
5990,1883-1889,0,Unprovoked,PANAMA,NaN,NaN,M,FATAL,Y
5991,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,Swimming,M,"FATAL. ""Shark bit him in half, carrying away t...",Y

In [8]:
fatal_count = data.Fatal.value_counts()
print(fatal_count)

N          4315
Y          1552
UNKNOWN      94
 N            8
#VALUE!       1
N             1
n             1
F             1
Name: Fatal, dtype: int64

In [15]:
data['Fatal'].fillna('UNKNOWN', inplace = True)

In [10]:
data['Fatal']= data['Fatal'].str.replace('n','N')
data['Fatal']= data['Fatal'].str.replace(' N','N')
data['Fatal']= data['Fatal'].str.replace('N ','N')

In [11]:
fatal_count = data.Fatal.value_counts()
print(fatal_count)

N          4325
Y          1552
UNKNOWN     113
#VALUE!       1
F             1
Name: Fatal, dtype: int64

In [12]:
data.loc[data['Fatal'] == 'UNKNOWN']

,Date,Year,Type,Country,Area,Activity,Sex,Injury,Fatal
54,02-Jun-16,2016,Unprovoked,AUSTRALIA,New South Wales,Spearfishing,M,"No injury, but sharks repeatedly hit their fin...",UNKNOWN
401,08-Sep-13,2013,Unprovoked,USA,South Carolina,NaN,F,No details,UNKNOWN
1047,20-Apr-08,2008,Unprovoked,AUSTRALIA,New South Wales,NaN,M,NaN,UNKNOWN
1142,Jul-07,2007,Invalid,SENEGAL,NaN,Murder,NaN,NaN,UNKNOWN
1844,Reported 03-Mar-2000,2000,Invalid,NEW ZEALAND,North Island,Kayaking,M,Reported as shark attack but probable drowning,UNKNOWN
2025,07-Jun-97,1997,Unprovoked,BRAZIL,Rio de Janeiro,Bathing,M,NaN,UNKNOWN
2035,21-Feb-97,1997,Unprovoked,USA,Hawaii,NaN,M,No details,UNKNOWN
2042,29-Dec-96,1996,Unprovoked,AUSTRALIA,Queensland,Surfing,M,NaN,UNKNOWN
2070,14-Jul-96,1996,Unprovoked,USA,Hawaii,NaN,NaN,No details,UNKNOWN
2082,28-Apr-96,1996,Unprovoked,USA,Hawaii,NaN,M,No details,UNKNOWN
2098,14-Jan-96,1996,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2103,18-Dec-95,1995,Unprovoked,USA,Hawaii,NaN,M,No details,UNKNOWN
2163,18-May-95,1995,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2179,1995,1995,Unprovoked,USA,South Carolina,NaN,M,No details,UNKNOWN
2184,Reported 10-Dec-1994,1994,Unprovoked,VANUATU,Tafea Province,NaN,NaN,No details,UNKNOWN
2317,Aug-92,1992,Invalid,USA,Florida,Fisherman,M,No details,UNKNOWN
2423,1990,1990,Unprovoked,USA,Florida,Surfing,M,NaN,UNKNOWN
2425,03-Dec-89,1989,Unprovoked,AUSTRALIA,Northern Territory,NaN,M,"No details, ""recovering in Darwin Hospital""",UNKNOWN
2436,01-Oct-89,1989,Unprovoked,AUSTRALIA,Victoria,Surfing,M,No details,UNKNOWN
2449,27-Jul-89,1969,Invalid,BERMUDA,NaN,Scuba diving,M,FATAL,UNKNOWN
2581,01-Oct-86,1986,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2657,19-Sep-84,1984,Unprovoked,USA,Florida,Swimming,NaN,No details,UNKNOWN
2675,01-Mar-84,1984,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2718,19-Apr-83,1983,Unprovoked,USA,Florida,Surfing,M,No details,UNKNOWN
2771,1982,1982,Boat,ITALY,Tyrrhenian Sea,Boat,M,No details,UNKNOWN
2773,1982,1982,Unprovoked,TUNISIA,Biserta,Spearfishing,NaN,No details,UNKNOWN
2781,17-Oct-81,1981,Unprovoked,USA,Florida,Surfing,M,No details,UNKNOWN
2813,Mar-81,1981,Unprovoked,BRAZIL,Rio de Janeiro,Diving,NaN,NaN,UNKNOWN
2816,07-Feb-81,1981,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2982,04-Oct-75,1975,Invalid,USA,California,Surfing,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...
5308,Reported 29-Jun-1901,1901,Invalid,YEMEN,Aden,Diving around anchored liner,M,NaN,UNKNOWN
5316,13-Sep-00,1900,Unprovoked,USA,Rhode Island,Diving,M,No injury,UNKNOWN
5355,Reported 1898,1898,Invalid,CRETE,NaN,Sponge divers,M,Unknown,UNKNOWN
5373,1897,1897,Unprovoked,EGYPT,Mediterranean Sea,NaN,NaN,No details,UNKNOWN
5411,21-Aug-1894,1894,Unprovoked,USA,New York,Swimming,F,No injury,UNKNOWN
5414,29-Jun-1894,1894,Unprovoked,USA,Florida,Bathing,M,"""Painfully injured"" but no details",UNKNOWN
5432,1893,1893,Unprovoked,EGYPT,Mediterranean Sea,NaN,NaN,No details,UNKNOWN
5437,24-Jun-1892,1892,Invalid,FRANCE,Brittany,Fishing boat,NaN,"No injury, no attack",UNKNOWN
5464,1890,1890,Unprovoked,INDIA,Tamil Nadu,Diving,M,No details,UNKNOWN
5465,1890,1890,Unprovoked,INDIA,Tamil Nadu,Diving,M,No details,UNKNOWN
5468,Reported 29-Nov-1889,1889,Invalid,GREECE,Northern Peloponnese,NaN,NaN,"Human remains found in 4m, 900 kg shark",UNKNOWN
5642,Reported 07-Aug-1872,1872,Invalid,CROATIA,NaN,Fishing,M,No injury,UNKNOWN
5697,04-Dec-1862,1862,Invalid,NEW ZEALAND,South Island,NaN,NaN,NaN,UNKNOWN
5699,Reported 02-Aug-1862,1862,Invalid,SPAIN,Malaga,NaN,M,Possible drowning and scavenging,UNKNOWN
5718,16-Mar-1859,1859,Unprovoked,USA,Hawaii,Fell overboard,M,FATAL,UNKNOWN
5726,06-Feb-1856,1856,Unprovoked,AUSTRALIA,Victoria,Swimming,M,Severe bite to thigh. Not known if he survived,UNKNOWN
5747,28-Jul-52,1852,Invalid,ATLANTIC OCEAN,NaN,NaN,F,Death preceded shark involvement,UNKNOWN
5793,Ca. 1837,1837,Invalid,USA,South Carolina,NaN,M,Shark caught contained human remains,UNKNOWN
5794,1836.07.26.R,1836,Invalid,SPAIN,NaN,NaN,NaN,"Shark caught, contained human remains",UNKNOWN
5795,1836.00.,1836,Unprovoked,AUSTRALIA,South Australia,NaN,NaN,"No details, it was the year the first settlers...",UNKNOWN
5820,Reported 22-May-1818,1818,Invalid,NORWAY,NaN,NaN,M,Probable drowning,UNKNOWN
5845,1755,1755,Unprovoked,SWEDEN,Skagerrak arm of the North Sea,NaN,M,NaN,UNKNOWN
5849,1733,1733,Invalid,ICELAND,Bardestrand,NaN,NaN,"Partial hominid remains recovered from shark, ...",UNKNOWN
5856,Reported 1638,1638,Unprovoked,NaN,NaN,NaN,M,NaN,UNKNOWN
5857,Reported 1637,1637,Unprovoked,INDIA,West Bengal,Wading,NaN,NaN,UNKNOWN
5858,Reported 1617,1617,Unprovoked,INDIA,West Bengal,NaN,NaN,NaN,UNKNOWN
5860,1595,1595,Unprovoked,INDIA,Kerala,Ship lay at anchor & man was working on its ru...,M,"Leg severed mid-thigh, hand severed, arm above...",UNKNOWN
5862,1555,1555,Unprovoked,NaN,NaN,Swimming,M,NaN,UNKNOWN
5863,Ca. 1554,1554,Unprovoked,FRANCE,Nice & Marseilles,NaN,M,NaN,UNKNOWN
5967,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,NaN,M,NaN,UNKNOWN

In [13]:
data.loc[data['Injury'] == 'No details']

,Date,Year,Type,Country,Area,Activity,Sex,Injury,Fatal
401,08-Sep-13,2013,Unprovoked,USA,South Carolina,NaN,F,No details,UNKNOWN
2035,21-Feb-97,1997,Unprovoked,USA,Hawaii,NaN,M,No details,UNKNOWN
2070,14-Jul-96,1996,Unprovoked,USA,Hawaii,NaN,NaN,No details,UNKNOWN
2082,28-Apr-96,1996,Unprovoked,USA,Hawaii,NaN,M,No details,UNKNOWN
2098,14-Jan-96,1996,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2103,18-Dec-95,1995,Unprovoked,USA,Hawaii,NaN,M,No details,UNKNOWN
2163,18-May-95,1995,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2179,1995,1995,Unprovoked,USA,South Carolina,NaN,M,No details,UNKNOWN
2184,Reported 10-Dec-1994,1994,Unprovoked,VANUATU,Tafea Province,NaN,NaN,No details,UNKNOWN
2317,Aug-92,1992,Invalid,USA,Florida,Fisherman,M,No details,UNKNOWN
2436,01-Oct-89,1989,Unprovoked,AUSTRALIA,Victoria,Surfing,M,No details,UNKNOWN
2581,01-Oct-86,1986,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2657,19-Sep-84,1984,Unprovoked,USA,Florida,Swimming,NaN,No details,UNKNOWN
2675,01-Mar-84,1984,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
2718,19-Apr-83,1983,Unprovoked,USA,Florida,Surfing,M,No details,UNKNOWN
2771,1982,1982,Boat,ITALY,Tyrrhenian Sea,Boat,M,No details,UNKNOWN
2773,1982,1982,Unprovoked,TUNISIA,Biserta,Spearfishing,NaN,No details,UNKNOWN
2781,17-Oct-81,1981,Unprovoked,USA,Florida,Surfing,M,No details,UNKNOWN
2816,07-Feb-81,1981,Unprovoked,AUSTRALIA,Western Australia,NaN,NaN,No details,UNKNOWN
3171,Apr-70,1970,Unprovoked,SOLOMON ISLANDS,NaN,Swimming,M,No details,UNKNOWN
3186,1970,1970,Unprovoked,CROATIA,Zadar County,Spearfishing,M,No details,UNKNOWN
3204,27-Jun-69,1969,Unprovoked,USA,Florida,Wading,M,No details,UNKNOWN
3216,Feb-69,1969,Invalid,AUSTRALIA,Queensland,Hard hat diving,M,No details,UNKNOWN
3319,14-Nov-66,1966,Unprovoked,THAILAND,NaN,NaN,NaN,No details,UNKNOWN
3422,Ca. 1965,1965,Invalid,SOUTH AFRICA,Eastern Cape Province,Bather,NaN,No details,UNKNOWN
3548,Early 1963,1963,Unprovoked,FIJI,Vita Levu,NaN,NaN,No details,UNKNOWN
4030,25-Mar-56,1956,Boating,ITALY,Ligurian Sea,Boating,NaN,No details,UNKNOWN
4043,1956,1956,Unprovoked,USA,Virginia,Swimming,F,No details,UNKNOWN
4084,1955,1955,Unprovoked,USA,Florida,NaN,NaN,No details,UNKNOWN
4097,02-Oct-54,1954,Boating,CROATIA,Zadar County,Boating,NaN,No details,UNKNOWN
4552,1940,1940,Invalid,SOUTH AFRICA,Eastern Cape Province,Swimming,NaN,No details,UNKNOWN
4559,09-Nov-39,1939,Boating,AUSTRALIA,New South Wales,NaN,NaN,No details,UNKNOWN
4560,06-Nov-39,1939,Boating,AUSTRALIA,New South Wales,NaN,NaN,No details,UNKNOWN
4768,11-Jan-32,1932,Boating,AUSTRALIA,Victoria,Fishing,NaN,No details,UNKNOWN
4799,1931,1931,Unprovoked,PAPUA NEW GUINEA,NaN,NaN,NaN,No details,UNKNOWN
4873,27-May-28,1928,Invalid,INDIA,NaN,NaN,M,No details,UNKNOWN
4928,1926,1926,Unprovoked,SOUTH AFRICA,Western Cape Province,Swimming to mail boat,M,No details,UNKNOWN
5114,1914,1914,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,NaN,F,No details,UNKNOWN
5373,1897,1897,Unprovoked,EGYPT,Mediterranean Sea,NaN,NaN,No details,UNKNOWN
5432,1893,1893,Unprovoked,EGYPT,Mediterranean Sea,NaN,NaN,No details,UNKNOWN
5464,1890,1890,Unprovoked,INDIA,Tamil Nadu,Diving,M,No details,UNKNOWN
5465,1890,1890,Unprovoked,INDIA,Tamil Nadu,Diving,M,No details,UNKNOWN
5583,3-Jul-1879,1879,Unprovoked,USA,California,Bathing,M,No details,N

In [17]:
data = data.drop(['], axis=1)

,Date,Year,Type,Country,Area,Activity,Sex,Injury,Fatal
0,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Minor injury to thigh,N
1,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to hands,N
2,18-Sep-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to lower leg,N
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Surfing,M,Struck by fin on chest & leg,N
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Surfing,M,No injury: Knocked off board by shark,N
5,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Fishing,NaN,Shark rammed boat. No injury to occupant,N
6,11-Sep-16,2016,Unprovoked,USA,Florida,Wading,M,Minor injury to arm,N
7,07-Sep-16,2016,Unprovoked,USA,Hawaii,Swimming,F,Severe lacerations to shoulder & forearm,N
8,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Kite surfing,M,FATAL,Y
9,05-Sep-16,2016,Unprovoked,USA,South Carolina,Boogie boarding,F,Lacerations & punctures to lower right leg,N
10,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Surfing,M,"No inury, board broken in half by shark",N
11,04-Sep-16,2016,Unprovoked,USA,Florida,Body boarding,M,Foot bitten,N
12,01-Sep-16,2016,Unprovoked,USA,California,Spearfishing,M,Two toes broken & lacerated,N
13,29-Aug-16,2016,Unprovoked,USA,Florida,Surfing,M,Lacerations to right foot,N
14,29-Aug-16,2016,Unprovoked,USA,Florida,Surfing,M,Minor injury to ankle,N
15,27-Aug-16,2016,Unprovoked,REUNION,NaN,Surfing,M,"Right arm severed, ankle severely bitten",N
16,25-Aug-16,2016,Unprovoked,USA,Florida,Wading,M,Minor injury to ankle,N
17,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Snorkeling,M,Lacerations to left leg,N
18,06-Aug-16,2016,Unprovoked,USA,Hawaii,SUP Foil boarding,M,"No inury, shark & board collided",N
19,04-Aug-16,2016,Unprovoked,USA,Florida,Surfing,M,Big toe bitten,N
20,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Swimming,M,Lacerations to right hand,N
21,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,Swimming,M,Lacerations to leg,N
22,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Kayaking,M,"No injury, shark nudged kayak repeatedly",N
23,27-Jul-16,2016,Provoked,USA,Florida,Lobstering,M,Laceration to left forearm PROVOKED INCIDENT,N
24,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,Surfing,M,"No injury. Leg rope severed, knocked off board...",N
25,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Surfing,M,Lacerations to left leg,N
26,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Surfing,M,Calf bumped but no injury,N
27,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Spearfishing,M,Lacerations to face and right leg,N
28,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,Fishing,M,Laceration to left calf from hooked shark PROV...,N
29,17-Jul-16,2016,Boat,USA,Alabama,Fishing in Alabama Deep Fishing Rodeo,NaN,"No injury, shark bit trolling motor",N
...,...,...,...,...,...,...,...,...,...
70,18-Apr-16,2016,Provoked,FRENCH POLYNESIA,Tuamotos,Spearfishing,M,"Severe lacerations to right forearm, hand and ...",N
71,13-Apr-16,2016,Unprovoked,USA,Florida,Spearfishing,M,Multiple bites to right arm,N
72,09-Apr-16,2016,Unprovoked,NEW CALEDONIA,Grand Terre,Walking,F,FATAL,Y
73,08-Apr-16,2016,Invalid,CAPE VERDE,Boa Vista Island,NaN,M,"""Serious""",N
74,07-Apr-16,2016,Unprovoked,USA,Florida,Fishing,M,Left hand bitten,N
75,07-Apr-16,2016,Invalid,USA,Florida,SUP,M,Fell off board when spinner shark leapt from t...,N
76,31-Mar-16,2016,Unprovoked,USA,Hawaii,Snorkeling,F,Minor injury to left foot,N
77,30-Mar-16,2016,Unprovoked,AUSTRALIA,New South Wales,Surfing,M,Severe injury to thigh,N
78,28-Mar-16,2016,Unprovoked,USA,Florida,NaN,M,Minor injury to arm. Possibly caused by smalll...,N
79,28-Mar-16,2016,Unprovoked,AUSTRALIA,New South Wales,Surfing,M,"No injury, board dented",N
80,26-Mar-16,2016,Provoked,BAHAMAS,NaN,NaN,M,Minor injury to chest PROVOKED INCIDENT,N
81,13-Mar-16,2016,Invalid,USA,California,Surfing,NaN,Board reportedly bumped by shark. No injury,N
82,11-Mar-16,2016,Unprovoked,USA,Florida,Body surfing,M,Lacerations to right foot and ankle,N
83,10-Mar-16,2016,Unprovoked,Fiji,Vanua Levu,Diving for beche-de-mer,M,FATAL,Y
84,04-Mar-16,2016,Unprovoked,USA,Florida,NaN,M,Superficial injury to foot,N
85,Reported 03-Mar-2016,2016,Unprovoked,AUSTRALIA,South Australia,Fishing,M,Puncture wounds to right calf,N
86,02-Mar-16,2016,Unprovoked,BRAZIL,Santa Catarina State,Swimming,M,Minor injury to head,N
87,22-Feb-16,2016,Unprovoked,NEW CALEDONIA,South Province,Kite surfing,M,Puncture wounds to right thigh,N
88,19-Feb-2016,2016,Unprovoked,NEW CALEDONIA,South Province,Spearfishing,M,Forearm bitten,N
89,12-Feb-16,2016,Unprovoked,DOMINICAN REPUBLIC,Altagracia Province,Wading,F,Avulsion injury to lower leg,N
90,Reported 10-Feb-2016,2016,Invalid,CAYMAN ISLANDS,Grand Cayman,Feeding stingrays?,M,Minor injury to wrist from Southern stingray,N
91,10-Feb-16,2016,Invalid,AUSTRALIA,Tasmania,Surfing,M,"No injury, knocked off board",N
92,05-Feb-16,2016,Unprovoked,AUSTRALIA,Queensland,Walking,F,Foot nipped,N
93,04-Feb-16,2016,Unprovoked,AUSTRALIA,New South Wales,Windsurfing,M,"No injury, shark bit board",N
94,29-Jan-16,2016,Boat,SOUTH AFRICA,KwaZulu-Natal,Kayak fishing,M,"No injury, shark capsized kayak",N
95,28-Jan-16,2016,Unprovoked,USA,Hawaii,Surfing,M,Lacerations to both hands,N
96,25-Jan-16,2016,Unprovoked,USA,Hawaii,Surfing,F,No injury,N
97,24-Jan-16,2016,Unprovoked,USA,Texas,Spearfishing,M,"Bruised ribs & tail bone, speargun broken and ...",N
98,24-Jan-16,2016,Boat,UNITED ARAB EMIRATES,Fujairah Emirate,Fishing,M,"No injury to occupants, shark leapt into boat",N
99,23-Jan-16,2016,Unprovoked,USA,Hawaii,Paddle boarding,M,No injury,N